INSERT INTO CATEGORIES (NAME) VALUES ('Alimentação');
INSERT INTO CATEGORIES (NAME) VALUES ('Transporte');
INSERT INTO CATEGORIES (NAME) VALUES ('Educação');
INSERT INTO CATEGORIES (NAME) VALUES ('Saúde');
INSERT INTO CATEGORIES (NAME) VALUES ('Lazer');
INSERT INTO CATEGORIES (NAME) VALUES ('Moradia');

INSERT INTO MEMBERS (NAME, ROLE, CREATED_AT) VALUES ('Alicia Silva', 'Esposa', NOW());
INSERT INTO MEMBERS (NAME, ROLE, CREATED_AT) VALUES ('Bruno Silva', 'Marido', NOW());
INSERT INTO MEMBERS (NAME, ROLE, CREATED_AT) VALUES ('Carla Souza', 'Filha', NOW());
INSERT INTO MEMBERS (NAME, ROLE, CREATED_AT) VALUES ('Daniel Souza', 'Filho', NOW());

INSERT INTO ROLES (AUTHORITY) VALUES ('ROLE_USER');
INSERT INTO ROLES (AUTHORITY) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES (AUTHORITY) VALUES ('ROLE_MANAGER');

INSERT INTO USERS (FIRST_NAME, LAST_NAME,EMAIL, PASSWORD) VALUES ('JOÃO','SILVA','JOAO@GMAIL.COM','123456');


INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Supermercado Extra', 250.75, '2025-06-01',0, 1, 1);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Posto Ipiranga', 150.00, '2025-06-03',1, 2, 2);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Mensalidade Escolar', 500.00, '2025-06-05',0, 3, 3);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Consulta Médica', 300.00, '2025-06-07',1, 4, 4);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Cinema', 80.00, '2025-06-10',0, 5, 1);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Aluguel', 1200.00, '2025-06-12',1, 6, 2);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Padaria Pão Quente', 45.50, '2025-06-15',0, 1, 3);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Uber', 60.00, '2025-06-18',1, 2, 4);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Curso de Inglês', 400.00, '2025-06-20',0, 3, 1);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Farmácia Saúde', 120.00, '2025-06-22',1, 4, 2);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Parque de Diversões', 150.00, '2025-06-25',0, 5, 3);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Conta de Luz', 200.00, '2025-06-28',1, 6, 4);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Mercado Municipal', 180.25, '2025-06-30',0, 1, 1);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Transporte Público', 90.00, '2025-07-02',1, 2, 2);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Apostila Escolar', 250.00, '2025-07-05',0, 3, 3);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Clínica Odontológica', 350.00, '2025-07-08',1, 4, 4);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Show Musical', 200.00, '2025-07-10',0, 5, 1);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Condomínio', 800.00, '2025-07-12',1, 6, 2);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Hortifruti', 95.75, '2025-07-15',0, 1, 3);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Manutenção do Carro', 250.00, '2025-07-18',1, 2, 4);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Aula de Música', 300.00, '2025-07-20',0, 3, 1);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Medicamentos', 180.00, '2025-07-22',1, 4, 2);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Teatro', 120.00, '2025-07-25',0, 5, 3);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Reforma da Casa', 1500.00, '2025-07-28',1, 6, 4);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Mercado Dia', 130.40, '2025-07-30',0, 1, 1);
