INSERT INTO CATEGORIES (NAME) VALUES ('Escola Rafaela');
INSERT INTO CATEGORIES (NAME) VALUES ('Uber');
INSERT INTO CATEGORIES (NAME) VALUES ('Abastecimento');
INSERT INTO CATEGORIES (NAME) VALUES ('Alimentação');
INSERT INTO CATEGORIES (NAME) VALUES ('Material Escolar');
INSERT INTO CATEGORIES (NAME) VALUES ('Condominio');
INSERT INTO CATEGORIES (NAME) VALUES ('Gás');
INSERT INTO CATEGORIES (NAME) VALUES ('Luz');
INSERT INTO CATEGORIES (NAME) VALUES ('Manutenção Carro');
INSERT INTO CATEGORIES (NAME) VALUES ('Farmácia');
INSERT INTO CATEGORIES (NAME) VALUES ('Supermercado');
INSERT INTO CATEGORIES (NAME) VALUES ('Cinema');
INSERT INTO CATEGORIES (NAME) VALUES ('Restaurante');
INSERT INTO CATEGORIES (NAME) VALUES ('Transporte Público');
INSERT INTO CATEGORIES (NAME) VALUES ('Consultas Médicas');
INSERT INTO CATEGORIES (NAME) VALUES ('Mensalidade Academia');
INSERT INTO CATEGORIES (NAME) VALUES ('Cursos');


INSERT INTO TB_ROLE (authority) VALUES ('ROLE_USER');
INSERT INTO TB_ROLE (authority) VALUES ('ROLE_ADMIN');
INSERT INTO TB_ROLE (authority) VALUES ('ROLE_CLIENT');

INSERT INTO TB_USER (first_name, last_name, email, phone, password) VALUES ('Elissandro','Aparecido Anastacio', 'elissandro@gmail.com', '41-995628454', '$2a$10$98IYctnO0aPdbPvrInNamePge53JwF9mbkDaYpqePf0YjVxaQGgGy');


INSERT INTO TB_USER_ROLE (user_id, role_id) VALUES (1, 1);
INSERT INTO TB_USER_ROLE (user_id, role_id) VALUES (1, 2);
