INSERT INTO CATEGORIES (NAME) VALUES ('Alimentação');
INSERT INTO CATEGORIES (NAME) VALUES ('Transporte');
INSERT INTO CATEGORIES (NAME) VALUES ('Educação');
INSERT INTO CATEGORIES (NAME) VALUES ('Saúde');
INSERT INTO CATEGORIES (NAME) VALUES ('Lazer');
INSERT INTO CATEGORIES (NAME) VALUES ('Moradia');

INSERT INTO MEMBERS (NAME, ROLE, CREATED_AT) VALUES ('Alicia Silva', 'Esposa', NOW());
INSERT INTO MEMBERS (NAME, ROLE, CREATED_AT) VALUES ('Bruno Silva', 'Marido', NOW());
INSERT INTO MEMBERS (NAME, ROLE, CREATED_AT) VALUES ('Carla Souza', 'Filha', NOW());
INSERT INTO MEMBERS (NAME, ROLE, CREATED_AT) VALUES ('Daniel Souza', 'Filho', NOW());

INSERT INTO ROLES (AUTHORITY) VALUES ('ROLE_USER');
INSERT INTO ROLES (AUTHORITY) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES (AUTHORITY) VALUES ('ROLE_MANAGER');

INSERT INTO USERS (FIRST_NAME, LAST_NAME,EMAIL, PASSWORD) VALUES ('JOÃO','SILVA','JOAO@GMAIL.COM','123456');

INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Supermercado Extra', 250.75, '2024-06-01',0, 1, 1);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Posto Ipiranga', 150.00, '2024-06-03',1, 2, 2);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Mensalidade Escolar', 500.00, '2024-06-05',0, 3, 3);
INSERT INTO TRANSACTIONS (DESCRIPTION, AMOUNT, DATE, TRANSACTION_TYPE, CATEGORY_ID, MEMBER_ID) VALUES ('Consulta Médica', 300.00, '2024-06-07',1, 4, 4);

